### ISSUE TITLE
Enrollment Error

### ISSUE THREAD

**Issue by Prabhatk97** [AntiAegis/Iris-Recognition#7]
As soon as I click the button "enroll" after entering the name and basic information, there is no message for successful enrollment instead the MATLAB command windows displays this error. 
![Error](https://user-images.githubusercontent.com/31854983/59635727-8331ff00-916f-11e9-8eb7-6ff19d0ccc04.png)

And after I click on the error from the command window, the MATLAB is unable to load the GUI.
![error2](https://user-images.githubusercontent.com/31854983/59635851-cf7d3f00-916f-11e9-8a38-d491bbd41e6a.png)

What could be the reason?

**Comment by AntiAegis** [comment]
Hi @Prabhatk97, 
Can you tell me which version of your Matlab?
Besides, did you use the App designer to run the GUI?

**Comment by Prabhatk97** [comment]
I'm currently using MATLAB R2016a. 
Yep I used the app designer, but it isn't loading the GUI.

**Comment by AntiAegis** [comment]
I see that the error said "Undefined function extractFeature for input arguments type char".
Maybe the path to the function extractFeature is not recognized.
Could you check it?

**Comment by Prabhatk97** [comment]
Thanks. I resolved that issue. But now, a different error is coming on creating account.
![Error3](https://user-images.githubusercontent.com/31854983/59754516-ddcc7780-92a3-11e9-8808-620ce8762343.png)

Do I need to make any changes here?
![error4](https://user-images.githubusercontent.com/31854983/59754578-fd63a000-92a3-11e9-940b-29c8c31c79db.png)

**Comment by AntiAegis** [comment]
Maybe you need to create a folder named 'template-database'

**Comment by Prabhatk97** [comment]
Yep. Thanks 
The issue has resolved.

**Comment by Prabhatk97** [comment]
On verifying the image which has been successfully enrolled, this error is coming:

![Error3](https://user-images.githubusercontent.com/31854983/59878612-62171b80-93c6-11e9-92a0-205808e1ac9f.png)

**Comment by AntiAegis** [comment]
Can you give more information about the error?
For example, the script line that the error has occurred.
