### ISSUE TITLE
EER_daugman.m

### ISSUE THREAD

**Issue by Prabhatk97** [AntiAegis/Iris-Recognition#8]
There is a file named "EER_daugman.m" in the fnc folder for the calculation of FAR and FRR. For this, how do I need to generate the files "result/HD_same_daughman.mat" and "result/HD_diff_daughman"?

![eer_daugman](https://user-images.githubusercontent.com/31854983/61518935-5e5bd080-aa28-11e9-9cb0-778bf7c6d9ff.png)

**Comment by AntiAegis** [comment]
Hi @Prabhatk97 ,

Regarding the Matlab version, I converted it from this page: https://www.peterkovesi.com/studentprojects/libor/sourcecode.html.

So you can go to the page and download the original source code and see how to generate files that you mentioned.

**Comment by Prabhatk97** [comment]
Actually, the original source code do not have the "EER_daugman" file. 
The file will be used for the calculation of FAR and FRR and will determine the performance of the system. 
Should I save the result of each of the images which are being verified separately?
