### ISSUE TITLE
Error when running verify.py

### ISSUE THREAD

**Issue by jeastudi** [AntiAegis/Iris-Recognition#9]
Dear, I write to request help with a python code error at the time of running. By console you ask me for arguments but previously those were defined in verify.py (image attachment) I would appreciate your help in due course.
![image](https://user-images.githubusercontent.com/38151088/63221902-c9a2da80-c16d-11e9-8ea4-8ae81e3ce2bb.png)

**Comment by AntiAegis** [comment]
Please try:
```
python verify.py --file 019_1_3.jpg
```
